# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'TradingGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TradingGame
  pod 'SwiftSocket'

  target 'TradingGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TradingGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
